/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHoTroKhachHang = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        lblDanhMuc = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        lblDatDo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-50.png"))); // NOI18N
        jLabel1.setText("Tên Tài Khoản");

        lblHoTroKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHoTroKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-customer-support-40.png"))); // NOI18N
        lblHoTroKhachHang.setText("Hỗ trợ Khách Hàng");
        lblHoTroKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoTroKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHoTroKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoTroKhachHangMouseExited(evt);
            }
        });

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-client-40.png"))); // NOI18N
        lblKhachHang.setText("Khách Hàng");
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseExited(evt);
            }
        });

        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-40.png"))); // NOI18N
        lblTrangChu.setText(" Trang chủ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseExited(evt);
            }
        });

        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-staff-40.png"))); // NOI18N
        lblNhanVien.setText("Nhân Viên");
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseExited(evt);
            }
        });

        lblDichVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-service-50.png"))); // NOI18N
        lblDichVu.setText("Dịch Vụ");
        lblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDichVuMouseExited(evt);
            }
        });

        lblDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-category-40.png"))); // NOI18N
        lblDanhMuc.setText("Danh Mục");
        lblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseExited(evt);
            }
        });

        lblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-food-bar-40.png"))); // NOI18N
        lblSanPham.setText("Sản Phẩm");

        lblDatDo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDatDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-create-order-40.png"))); // NOI18N
        lblDatDo.setText("Đặt Đồ");
        lblDatDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDatDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDatDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1086, 1086, 1086)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrangChu)
                            .addComponent(lblKhachHang))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNhanVien)
                                .addGap(68, 68, 68)
                                .addComponent(lblDanhMuc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHoTroKhachHang)
                                .addGap(18, 18, 18)
                                .addComponent(lblDichVu)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSanPham)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblDatDo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTroKhachHang)
                    .addComponent(lblTrangChu)
                    .addComponent(lblDichVu)
                    .addComponent(lblSanPham))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachHang)
                    .addComponent(lblNhanVien)
                    .addComponent(lblDanhMuc)
                    .addComponent(lblDatDo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Screenshot 2025-07-13 205557.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        // TODO add your handling code here:
        lblTrangChu.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseExited
        // TODO add your handling code here:
        lblTrangChu.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblTrangChuMouseExited

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseEntered
        // TODO add your handling code here:
        lblKhachHang.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblKhachHangMouseEntered

    private void lblKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseExited
        // TODO add your handling code here:
        lblKhachHang.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblKhachHangMouseExited

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        // TODO add your handling code here:
        setContentPane(new KhachHangJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseEntered
        // TODO add your handling code here:
        lblDanhMuc.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblDanhMucMouseEntered

    private void lblDanhMucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseExited
        // TODO add your handling code here:
        lblDanhMuc.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblDanhMucMouseExited

    private void lblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseClicked
        // TODO add your handling code here:
        setContentPane(new DanhMucJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblDanhMucMouseClicked

    private void lblHoTroKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoTroKhachHangMouseEntered
        // TODO add your handling code here:
        lblHoTroKhachHang.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblHoTroKhachHangMouseEntered

    private void lblHoTroKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoTroKhachHangMouseExited
        // TODO add your handling code here:
        lblHoTroKhachHang.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblHoTroKhachHangMouseExited

    private void lblHoTroKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoTroKhachHangMouseClicked
        // TODO add your handling code here:
        setContentPane(new HoTroKhachHangJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblHoTroKhachHangMouseClicked

    private void lblDatDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatDoMouseEntered
        // TODO add your handling code here:
        lblDatDo.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblDatDoMouseEntered

    private void lblDatDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatDoMouseExited
        // TODO add your handling code here:
        lblDatDo.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblDatDoMouseExited

    private void lblDatDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatDoMouseClicked
        // TODO add your handling code here:
        setContentPane(new DatDoJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblDatDoMouseClicked

    private void lblDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseEntered
        // TODO add your handling code here:
        lblDichVu.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblDichVuMouseEntered

    private void lblDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseExited
        // TODO add your handling code here:
        lblDichVu.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblDichVuMouseExited

    private void lblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseClicked
        // TODO add your handling code here:
        setContentPane(new DichVuJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblDichVuMouseClicked

    private void lblNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseEntered
        // TODO add your handling code here:
        lblNhanVien.setForeground(Color.WHITE); // đổi màu
    }//GEN-LAST:event_lblNhanVienMouseEntered

    private void lblNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseExited
        // TODO add your handling code here:
        lblNhanVien.setForeground(Color.BLACK); // hoặc màu mặc định
    }//GEN-LAST:event_lblNhanVienMouseExited

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
        // TODO add your handling code here:
        setContentPane(new NhanVienJPanel());
        revalidate(); // cập nhật lại code chhayj home
    }//GEN-LAST:event_lblNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDatDo;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblHoTroKhachHang;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTrangChu;
    // End of variables declaration//GEN-END:variables

    void showHomeJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void showHomePanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
